ossf/osv-schema

schema.md
Change the requirement to an "introduced" event, as a single "fixed"
event is likely made in mistake. That is, the following means nothing is
affected:
```json
{
"events": [
{"fixed": "0.5"}
]
}
```
=> Clarification to required entry types for the "events" array.

docs/schema.md
Mostly removed trailing comma in the JSON examples.
=> Fix invalid JSON examples

docs/schema.md
The repo attribute is not defined as property within the affected array but within an object of a ranges array.
=> Rearrange repo attribute in example

README.md
We recently renamed the Universal Vulnerability Identifier (UVI) project to Global Security Database (GSD)
=> Update UVI to GSD

docs/schema.md
Follow up to #13, noticed that I missed the Github pages reference.
=> Rename UVI to GSD within Github Pages

docs/schema.md, validation/schema.json
This adds a top-level `database_specific` field to allow source databases to embed custom metadata that is relevant to the entire vulnerability rather than specific affected products.
=> Add top-level database_specific field

docs/schema.md
This adds [Hex](https://hex.pm/) to the documented list of defined ecosystems. The description is the wording taken directly from their website, but open to feedback if you'd like it to follow a specific pattern.
There are no validations on the ecosystems defined in the schema docs, so the validation JSON has not been updated.
=> add Hex to the ecosystems for our erlang advisories

docs/schema.md, validation/schema.json
This resolves a semantic issue: Not all ecosystems that recommend using SemVer 2.0 for versioning actually enforce that format on version numbers, but it may still be possible for the ecosystem to determine which versions are affected based on a range of SemVer-like versions. To address this, after speaking with @oliverchang, we are proposing dropping the validation of a `versions` requirement for `ECOSYSTEM` ranges, and changing the documentation to state that versions are strongly recommended for when using `ECOSYSTEM` ranges but not required. They are still required for `GIT` ranges.
=> Drop versions requirement for `ECOSYSTEM` ranges

docs/schema.md, validation/schema.json
It will be helpful as this schema evolves to be able to distinguish between which version a particular vulnerability was exported against. This provides downstream consumers with the ability to decide how to import a vulnerability as well as provide some protection against any future breaking schema changes.
There is currently no standard or recommended best practice for versioning JSON schemas, so I made two decisions in this PR that perhaps require further discussion:
1. Naming the field `schema_version` versus `version` - Since we're dealing with affected product versions it seemed better to be explicit about the purpose of this field so as not to introduce any ambiguity or chance for misinterpretation.
2. Using SemVer format for indicating the schema version - It seems like the OSV …
=> Add a schema_version field for tracking which version of OSV Schema a vulnerability was produced against

docs/schema.md
In my understanding the OSV json is an invalid specification version 1.0.0 example, since it lakes a `versions` field and does not have a range of a SemVer 2.0 type:
> In short, each object in the `affected` array must contain either a non-empty
> `versions` list or at least one range in the `ranges` list of type `SEMVER`.
Dropping the `versions` requirement in #18 makes it valid although only for parsers that support the specification as of 1.1.0. Or have I missed something?
=> Invalid OSV json example

docs/schema.md, validation/schema.json
This proposes a top-level credits field. We learned through internal research projects that credits are an important form of currency in the vulnerability community, and often a strong motivator for identifying or fixing vulnerabilities. It provides the benefit of name recognition as well as acts as a resume of sorts for vulnerability researchers. In order to proved proper credit, it's important that contributors are able to be represented with both a name as well as unique identifiers or ways to link back to other work they have done.
Because of this, we chose to implement credits as a list of objects rather than strings for a few reasons:
1. Contributors may not want their personal email addresses published, so we don't want to rely on simple lists of "First Last <email...>" values.
2. …
=> Add credits field

docs/schema.md, validation/schema.json
This adds a top-level `severity` array field field to capture vulnerability severity rankings such as [CVSS](https://www.first.org/cvss/). Each severity is an object with a `type` enum and a `score`.
Initially supported types are `CVSS_V3` and `PLAIN_TEXT`, described in the schema documentation.
=> Add optional top-level severity field

docs/schema.md
Also clarify spec to state that the CVSS "score" is the vector string.
=> Update examples and add changelog for 1.2.0.

docs/schema.md
As a part of effort of exporting Android Security Bulletin (ASB) CVEs to OSV, we would need a new ecosystem for Android. This pull request is for updating the OSV schema description to add "Android" as a new ecosystem for ASB CVEs.
=> Add "Android" ecosystem.

docs/schema.md
Also fix the RUSTSEC link while we're here.
=> Update database prefixes to include GHSA.

docs/schema.md, validation/schema.json
=> Add `last_affected` event type.

docs/schema.md, validation/schema.json
This is intended only for metadata that enables databases to 
better convert OSV entries back into their original representation.
Part of #35.
=> Add database_specific to `affected[].ranges[]`.

docs/schema.md
Github Security Advisory  Dabatase is now using OSV format.
=> Update info about GitHub Security Advisory DB

README.md, docs/schema.md
This PR adds reference to the LoopBack Advisory Database.
As part of the ongoing security-related enhancement works, LoopBack is currently setting up its own advisory database for Node.js modules under its purview.
We're working to republish existing advisories under machine-readable formats (which includes OSV) and with the `LBSEC-` prefix.
see: https://github.com/loopbackio/security/issues/14
=> feat: add LoopBack Advisory Database

docs/schema.md
To properly account for multiple ranges. Fixes #44.
=> Fix evaluation algorithm

tools/debian/first_package_finder.py
Dockerfile runs python 3.8, so can't use removeprefix, which only got added in 3.9
=> Replace removeprefix since it doesn't exist in 3.8

tools/debian/convert_debian.py
The git repository for webwml must be the full repository, not `--depths=n` for modified date to be not null
=> add modified date entry to convert_debian output from git history

tools/debian/convert_debian.py
We were only checking for .data file modifications (mainly because of performance cost), now with the new method also checking for .wml file modifications and getting the latest modification have minimal performance cost.
=> Also check for modification of .wml files (the description)

tools/debian/first_package_finder.py
first_package_finder instead of creating one file per package per release, we create only one file per release
=> Export less files

docs/schema.md
This adds [GitHub Actions](https://docs.github.com/en/actions) and [Pub](https://pub.dev/) to the documented list of defined ecosystems in order to support GitHub's security advisories.
There are no validations on the ecosystems defined in the schema docs, so the validation JSON has not been updated.
cc: @katblag
=> Add GitHub Actions and Pub to the ecosystems list

docs/schema.md, validation/schema.json
Signed-off-by: Kurt Seifried <kurt@seifried.org>
=> Added CVSS_V2 and fixed whitespace

validation/schema.json
Loosen schema requirement for versions array, since it should be valid OSV to have just git commit ranges.
Fixes #79
Signed-off-by: Rex P <106129829+another-rex@users.noreply.github.com>
=> Loosen schema requirement for versions array

validation/schema.json
Some of the existing entries use null instead of being an empty array or removing the entry entirely.
=> Allow null instead of an empty array.

docs/schema.md, validation/schema.json
Based on https://github.com/ossf/osv-schema/issues/40#issuecomment-1371719724
=> Add optional severity field override for affected packages. 

docs/schema.md
add [conan.io](https://conan.io) ecosystem as an ecosystem entry in the ovs schema.
=> - add conan.io ecosystem

docs/schema.md, validation/schema.json
As discussed in https://github.com/ossf/osv-schema/issues/85, we'd like to propose these changes to the OSV schema to add credit types/roles that correspond to those defined by the [MITRE CVE schema](https://github.com/CVEProject/cve-schema/blob/master/schema/v5.0/CVE_JSON_5.0_schema.json).
Would appreciate any feedback or proposed changes!
=> Add a credit types field

docs/schema.md
Its omission was an oversight.
=> Include last_affected in fields discussed for affected[].ranges[].type

docs/schema.md
Add Rocky Linux ecosystem and RLSA/RXSA for Rocky Linux security advisories
=> Add Rocky Linux

docs/schema.md
Not an array. This is how the JSON schema and examples provided encodes this.
=> Clarify that the credits type field is a string.

docs/schema.md
Hi! We've prepared [a tool](https://github.com/AlmaLinux/errata2osv) to convert AlmaLinux errata information into shared OSV format. Serving shared format [here](https://github.com/AlmaLinux/osv-database). Could you review the data files we initialized out repository with? We tried to comply with OSV schema as much as possible, but would be pleased to receive any feedback.
The PR reserves ID tags and ecosystem name that AlmaLinux is aimed to use for OSV database.
=> Add AlmaLinux ecosystem

validation/schema.json
Fixes #52 
Per https://github.com/ossf/osv-schema/pull/132#issuecomment-1489414045, the OSV schema must be fully backwards interoperable, meaning using main instead of a specific version tag is the sanest option.
=> Add schema $id

docs/schema.md, validation/schema.json
Revisiting #89
Partially Fixes #78
Related to #137
=> Add DISCUSSION reference type

docs/schema.md
Rather than a generic description, updated the table to provide more specific (and actionable) information:
- Prefix
- Database Name / Source URL
- Canonical URL for a given \<ID>
- API Endpoint for a given \<ID>
- Regex for the ID
May not be fully complete or accurate, but should provide more actionable guidance for OSV consumers and producers.
=> Update database prefix documentation to be more detailed

validation/README.md, validation/schema.json
- Add `"additionalProperties": false` to help catch invalid fields.
- Validate RFC3339 timestamps.
- Validate CVSS scores.
=> Improve JSON schema.

README.md, docs/schema.md
There is a Haskell Security Response Team which is now in the process of defining a repository for security advisories, similar to how Rust handles these. As part of this, we decided to also integrate with OSV while we set things up. This should close https://github.com/haskell/security-advisories/issues/4
There are a few more TODOs left in the PR, partially waiting for https://github.com/haskell/security-advisories/pull/33#pullrequestreview-1473728366, partially waiting for a first pass over the PR. I'll try to fill in as much as possible before this can get merged.
=> Add Haskell ecosystem vulnerability and advisory types

docs/schema.md
We are in the process of creating/publishing our own CVE feed based on OSV schema for the [Bitnami catalog](https://bitnami.com/), but we would like to start the review process for a `Bitnami` ecosystem key. Do not hesitate to ask any questions you may have.
=> [bitnami] Adds ecosystem and prefix for Bitnami

docs/schema.md
This is a first pass at further clarifying the `"last_affected"` field and addressing #146 and #150. 
Preview is available [here](https://hayleycd.github.io/osv-schema/#requirements)
=> Clarified last_affected

README.md, docs/schema.md
As discussed in #105 earlier. I'm also using the ecosystem field in existing advisories: https://github.com/captn3m0/photon-os-advisories/blob/main/advisories/PHSA-2016-0006.json
Advisories are already published in OSV format: https://github.com/captn3m0/photon-os-advisories/tree/main/advisories (And Automated).
I'll get those enriched over time, but this could be merged in the interim.
Signed-off-by: Nemo <commits@captnemo.in>
=> [photon-os] Adds ecosystem and prefix for Photon

docs/schema.md
Hopefully wraps up #150 and #146 
View rendered example [here](https://hayleycd.github.io/osv-schema/#last_affected-vs-fixed-example). 
Changes were also made to the [affected.ranges.events fields](https://hayleycd.github.io/osv-schema/#affectedrangesevents-fields) to bring the formatting into line with the rest of the document. Fields were being rendered like this: `"last_affected"` where `last_affected` is preferred.
=> Add last_affected example for clarity

tools/ghsa/Pipfile.lock, tools/ghsa/README.md, tools/ghsa/convert_ghsa.py, tools/ghsa/dump_ghsa.py, tools/ghsa/testdata/equals_no_patch.osv.json, tools/ghsa/testdata/equals_with_patch.osv.json, tools/ghsa/testdata/full_ranges.osv.json, tools/ghsa/testdata/greater_than_equals_no_patch.osv.json, tools/ghsa/testdata/less_than_equals_no_patch.osv.json, tools/ghsa/testdata/less_than_equals_with_patch.osv.json, tools/ghsa/testdata/maven_greater_than.osv.json, tools/ghsa/testdata/multiple_ranges_in_package.osv.json, tools/ghsa/testdata/npm_greater_than.osv.json, tools/ghsa/testdata/pypi_normalize.osv.json, tools/ghsa/testdata/withdrawn.osv.json
- Bump `Pipfile.lock` with current dependencies (this allows installation)
- rename `osv` to `entry` to avoid shadowing the `osv` import
- add an option to pass in `--query` from the command line to manual set query parameters
=> Get GHSA importer working against with some minor tweaks

validation/schema.json
Based on conversation on #168, the CVSS validation by pure regex is too strict, so remove.
Fixes: #168
=> Remove CVSS validation

README.md, docs/schema.md
Closes #175.
I didn't quite understand "Source URL" vs. "OSV Formatted URL" so I took a guess.
cc @tylfin as upstream maintainer. I marked this as "unofficial" despite R Consortium backing, please CMIIW.
=> Add CRAN+Bioconductor ecosystems

docs/schema.md
Also fix OSV formatted URL for RSEC with `vulns` path
Per comment: https://github.com/ossf/osv-schema/issues/175#issuecomment-1647362745
=> Add example RSEC vulnerability to schema document

docs/schema.md
Per
https://developer.apple.com/documentation/packagedescription/package/dependency
https://docs.swift.org/package-manager/PackageDescription/PackageDescription.html#package-dependency
Putting "URL" in the name to make this consistent with how it's actually defined using `Package.Dependency`. 
There are some changes coming as part of https://github.com/apple/swift-evolution/blob/main/proposals/0292-package-registry-service.md, and we'll likely need to define a new ecosystem for that once it's finalized, as it looks like the identifiers are moving to a `Scope.Name` format. 
Fixes #170.
=> Add SwiftURL ecosystem.

README.md, docs/schema.md
Related to: https://github.com/psf/advisory-database/pull/9
=> Add 'PSF' OSV ID prefix for Python Software Foundation database

docs/schema.md
Android package name definition now points to the git project affected and where the patches should be applied to instead of bulletin components.
Remove the Android Ecosystem Components appendix.
=> Update Android ecosystem package name definition.

docs/schema.md
I had left 2 TODOs to add JSON examples. Filling them now (will redo the GHC one when we get a real GHC issue) and closing
https://github.com/haskell/security-advisories/issues/4.
=> Fill in TODOs in Haskell parts of osv-schema

docs/schema.md
@Roo4L from AlmaLinux suggested we explain why aliases shouldn't be used for bundling.
I've added a sentence based on their suggestion.
=> Clarify why aliases should not be used in vulnerability bundles

CHANGELOG.md, README.md, docs/schema.md
- Make Purpose section more concise. We don't need a history lesson here anymore :) 
- Remove old changelogs.
- Alphabetically sort databases and ecosystems.
- Add some missing databases (Curl, NVD).
=> Some schema cleanup.

docs/schema.md, validation/schema.json
This PR comes to unlock #166 which seems stuck.
Basic support of CVSS v4.0, I'll open another issue about #178 about validating the CVSS vectors soon, as the FIRST.ORG SIG CVSS provide official CVSS validation regex we could use for schema validation.
The string representation (aka vector) example comes from the CVSS v4.0 Specification Document Section 7.
=> Add support of CVSS v4.0

README.md, docs/schema.md
=> Add Ubuntu ecosystem

docs/schema.md
Rationale: reduce the amount of false negatives in commits belonging to branches forked in-between `introduced` and `fixed`/`limit`.
Closes #216.
=> Events requirements: recommend the use of `fixed` over `limit`

docs/schema.md
Adds back the `as defined by the database` in the description of the `range` object's `database_specific` field. This brings it into line with the descriptions of the other two `database_specific` fields. I suspect it was just a bad copy/paste operation as we were adding those fields to other objects beyond the top level.
=> Fix truncated copy/paste in database_specific description

CHANGELOG.md, docs/schema.md
=> Enable encoding of Maven registries.

tools/ghsa/convert_ghsa.py
OSV has support for `last_affected` for when we know which version was the last to be vulnerable.
The GHSA converter previously skipped adding this range event because `last_affacted` didn't exist at the time.
This change implements `last_affected` support for GHSA.
=> Add support for last_affected in GHSA conversions to OSV.

validation/README.md
It does users a disservice to direct them to `check-jsonschema` in the first instance.
`check-jsonschema` is incredibly slow (probably because of Python interpreter startup time) when run in a loop on multiple files.
=> Mention a more performant JSON validator

docs/schema.md
Based on query raised in https://github.com/google/osv.dev/issues/2135
=> Enhance discussion of affected[].version formats

docs/schema.md
Coming out of https://github.com/google/osv.dev/issues/2374#issuecomment-2218339823, wanted to suggest some potential wording improvements to help the next Linux distro that comes along better understand how the `aliases` field should and should not be used.
I welcome any feedback, and I'm not sure I've captured the sentiment perfectly. 
One particular callout: this PR removes an existing sentence (below) that we struggled to wrap our heads around. If there's something that this was trying to convey that's lost in my PR, I'd love to better understand it.
>Aliases may be used for vulnerabilities affecting different packages or ecosystems as long as they follow this definition.
cc: @michaelkedar @andrewpollock @cpanato
=> add clarity around distros' use of aliases

validation/schema.json
Addresses undetected invalidity surfaced in
https://github.com/github/advisory-database/blob/adf108ed87cfbe666a56cd9cab986afc3854150e/advisories/github-reviewed/2023/11/GHSA-jjfh-589g-3hjx/GHSA-jjfh-589g-3hjx.json and helps address https://github.com/google/osv.dev/issues/2369
h/t @gregsdennis for assistance with the validation syntax
This uses the regexes from the [official schema definitions for CVSS](https://www.first.org/cvss/data-representations), with some additional slash-escaping that regex101.com seemed to feel was necessary to make them valid.
```
$ git -C ~/gosst/osv/advisory-database/ checkout adf108ed87cfbe666a56cd9cab986afc3854150e
HEAD is now at adf108ed87c Publish GHSA-jjfh-589g-3hjx
$ ~/go/bin/jv ./validation/schema.json …
```
=> Add validation for CVSS

CHARTER.md
This PR resolves #224 
The mission specifically needs review.
=> Charter for review

docs/schema.md, validation/schema.json
Per discussion offline, this updates Android vulnerability ID prefixes to corresponds with reality. This may need to be revisited in the future (e.g. `ASB-A` -> `A-ASB`) but that would be a separate effort.
=> Update Android IDs and links in schema table.

docs/schema.md
Fix incorrect version number (it was one patch version too high), and update the date.
=> Prepare for release again

.github/workflows/validate-schema.yml
I'm not actually sure how I came to pin at a version less than the latest...
This should fix the problem seen in https://github.com/dsanders11/json-schema-validate-action/issues/20
Signed-off-by: Andrew Pollock <apollock@google.com>
=> fix(workflow): use v1.2.0 of json-schema-validate-action

tools/osv-linter/go.mod, tools/osv-linter/go.sum, tools/osv-linter/internal/linter.go
Address UX expectation surfaced by @another-rex
When invoked with no filenames or with a hyphen, read from stdin.
```
$ cat test_data/CVE-2018-5407.json | go run ./cmd/osv record lint -
Running "ALL" check collection on &["-"]
Running "introduced-event-exists" check on "<stdin>"
Running "range-is-distinct" check on "<stdin>"
Running "package-exists" check on "<stdin>"
2024/09/04 02:14:15 "<stdin>": "package-exists": []checks.CheckError{checks.CheckError{Code:"P0001", Message:": package \"openssl\" not found in \"Alpine\""}}
Running "package-versions-exist" check on "<stdin>"
2024/09/04 02:14:15 "<stdin>": "package-versions-exist": []checks.CheckError{checks.CheckError{Code:"P0002", Message:": Failed to find some versions of openssl: &errors.errorString{s:\"unsupported ecosystem: …
```
=> feat(osv-linter): support checking stdin

docs/schema.md, validation/schema.json
Our recommended (SUSE-RU) and feature (SUSE-FU) updates occasionaly includes also security fixes. We will only generate OSV entries for the ones which CVEs.
=> feat(suse): allow more SUSE- prefixes

docs/schema.md, validation/schema.json
Some optional updates (`SUSE-OU-`) also include security fixes, example: https://ftp.suse.com/pub/projects/security/osv/SUSE-OU-2015%3A1803-1.json
=> feat(suse): add `SUSE-OU-` prefixes

docs/schema.md
This improves readability.
Also @oliverchang I believe CGA is missing in validation/schema.json
=> Fix order of prefixes in docs/schema.md

tools/redhat/.pylintrc, tools/redhat/.style.yapf, tools/redhat/Pipfile, tools/redhat/Pipfile.lock, tools/redhat/README.md, tools/redhat/convert_redhat.py, tools/redhat/convert_redhat_test.py, tools/redhat/csaf.py, tools/redhat/csaf_test.py, tools/redhat/osv.py, tools/redhat/osv_test.py, tools/redhat/testdata/RHSA-2024_4546.json, tools/redhat/testdata/rhsa-2015_0008.json, tools/redhat/testdata/rhsa-2024_4546.json
Add a Red Hat CSAF to OSV converter tool used by Red Hat to produce the Red Hat OSV data to be hosted at https://security.access.redhat.com/data/osv
This is slightly modified version of the sample code originally review at https://github.com/andrewpollock/rhcsaf2osv
=> add Red Hat converter

docs/schema.md
Adjust Red Hat IDs to be correct per what's [validated by the schema](https://github.com/ossf/osv-schema/blob/0cef5d4bb1d6d76b7d8392b192f6e160c569e6e4/validation/schema.json#L309)
=> adjust schema docs to have correct Red Hat IDs

tools/osv-linter/cmd/osv/main.go, tools/osv-linter/internal/checks/checks.go, tools/osv-linter/internal/checks/packages.go, tools/osv-linter/internal/checks/ranges.go, tools/osv-linter/internal/linter.go, tools/osv-linter/internal/pkgchecker/ecosystems.go
- Add a `--verbose` flag to tone down the output
- Clean up how the findings are presented
- Discovered the Alpine ecosystem was being overlooked in error
```
$ go run ./cmd/osv record lint test_data/
test_data/nointroduced-CVE-2023-41045.json:
* [R0001]: missing 'introduced' object in event
test_data/nondistinct-CVE-2018-5407.json:
* [R0002]: overlapping event: "e818b74be2170fbe957a07b0da4401c2b694b3b8"
test_data/nopackage-GHSA-9v2f-6vcg-3hgv.json:
* [P0001]: package "Gradi0" not found in "PyPI"
* [P0002]: Failed to find some versions of Gradi0: &errors.errorString{s:"unable to validate package: fail: \"https://pypi.org/pypi/gradi0/json\": bad response: 404"}
2024/09/04 06:42:12 found errors
exit status 1
```
=> refactor(osv-linter): tidy up human output

tools/redhat/redhat_osv/csaf.py, tools/redhat/redhat_osv/osv.py, tools/redhat/redhat_osv/osv_test.py, tools/redhat/testdata/rhsa-2003_315.json
Some old flaws have no 'scores' field at all. In that case create the CSAF object with the cvss_v3_attributes set to an empty string.
=> account for older flaws which had no scores

tools/redhat/README.md, tools/redhat/redhat_osv/osv.py, tools/redhat/redhat_osv/osv_test.py, tools/redhat/testdata/RHSA-2024_4546.json
@andrewpollock As discussed, removing version and other qualifiers from package  PURL in Red Hat data.
=> No purl version

tools/redhat/redhat_osv/osv.py, tools/redhat/testdata/RHSA-2024_4546.json
Including the arch suffix in a fixed version can cause false positives if the wrong arch range is used to scan a system.
For example
`0:7.3.0-427.28.1.el9_4.aarch64` < `0:7.3.0-427.28.1.el9_4.ppc64le`
So `0:7.3.0-427.28.1.el9_4.aarch64` would match the `0..0:7.3.0-427.28.1.el9_4.ppc64le` range and be considered vulnerable
=> strip arch from version and deduplicate arch agnostic packages

README.md, docs/schema.md, tools/debian/.pylintrc, tools/ghsa/convert_ghsa.py, tools/osv-linter/internal/checks/checks.go
These are all very minor but still typos none the less
=> chore: address some typos

.github/workflows/checks.yml
This setups up a workflow for running the `osv-linter` tests for pull requests - it looks like there are also tests for the Python-based tools, which I'll look into as a follow up.
This'll make it easier to later add CI for #292
=> ci: run `osv-linter` tests

tools/redhat/redhat_osv/osv.py
For records like RHSA-2024:8116, `.affected[]` was ending up with the packages multiple times
=> fix(redhat_conversion): avoid repeated package entries

tools/redhat/redhat_osv/convert_redhat_test.py, tools/redhat/redhat_osv/csaf.py, tools/redhat/testdata/RHSA-2024_6220.json, tools/redhat/testdata/rhsa-2024_6220.json
Sometimes RPMs are packed in a module. It's a little harder to detect the actual modules themselves on a running system, but we can still check their RPMs. This change allows skipping modules, but keeps their RPM children.
=> skip modules but keep their rpms

docs/schema.md
The table is pretty important but currently you can't actually link directly to it, so this adds a header for that
=> feat: add dedicated header for ecosystems table

validation/schema.json
This introduces new dedicated types for the name of an ecosystem (which is an enum) and an ecosystem suffix (which is a string starting with `:`), along with renaming the existing `ecosystem` type to `ecosystemWithSuffix` (+ adding it).
While these types are not actually used in the schema due to JSONSchema currently does not have a way of specifying that a string is made up of two types, having them defined enables a lot of automation as the current `pattern` based type cannot be used to get a finite list of all possible ecosystems defined by the spec.
As an example, here's a [TypeScript playground](https://www.typescriptlang.org/play/?#code/C4TwDgpgBAogxgewM4icCBbKBeKByOAJwEN0kA6ASwTygB98BxG+-AWWIDcIA7PAWABQQ0JFiIUaTAHVKwABYAFQhABmlAB45xyVOiwMABgBIA3vF1SMAXwBcZtIUo8A5tYfAnr64YDcQoQATCDgA …
=> feat: create dedicated ecosystem name enum with all ecosystems

docs/schema.md
PURLs should not include the `@version` component when used in OSV. 
`affected[].ranges[]`  should be used for this purpose.
=> Clarify PURL requirements.

validation/schema.json
This reformates the JSON schema file to reduce the diff on #303 since currently there's a section that is incorrectly indented
=> refactor: reformat osv schema json

tools/osv-linter/README.md
This commit adds a README.md to provide interested parties with some further details and guidance about the OSV linter
=> docs(osv-linter): Add a README.md

bindings/go/osvschema/constants.go
This is defined in the schema but we don't have a constant for it
=> fix: add missing `GIT` reference constant

tools/osv-linter/internal/pkgchecker/ecosystems.go
Adds Red Hat and SUSE/openSUSE and sorts consistent with case insensitive sort of OSV.dev's `ecosystems.txt`
=> feat(osv-linter): add stubs for all current defined ecosystems

tools/osv-linter/internal/checks/packages.go, tools/osv-linter/internal/checks/packages_test.go, tools/osv-linter/test_data/MAL-2024-10238.json
This corrects a bug where the ecosystem allowlist was not working correctly when not set, and so ecosystem checks were not being run at all.
=> fix(linter): handle ecosystem allowlist correctly

validation/schema.json
`affected[].severity` mentions:
'If any package level severity fields are set,
the top level severity must not be set.'
This change updates the JSON schema under validation to reflect this.
Changes have been tested with both tools mentioned under validation/README.md
=> Update JSON schema to reflect top-level/package severities mutual exclusivity

README.md
I first discovered this repo from a link over at Hackernews, but it wasn't clear what OSV was. After clicking around a bit I found this statement on the [osv.dev](https://osv.dev/) homepage:
This PR simply adds the highlighted short description to the top of this repo's README. This should help new readers get a quick and basic understanding of what OSV is without having to leave this repo.
If the maintainers of this repo feel that this PR isn't necessary, just go ahead and close it -- you won't hurt my feelings 😄
=> Help new readers quickly understand what OSV is.

bindings/go/osvschema/constants.go, docs/schema.md, ecosystems.json, tools/osv-linter/internal/pkgchecker/ecosystems.go, validation/schema.json
Adding `Kubernetes` ecosystem according to the discussion [here](https://github.com/kubernetes-sigs/cve-feed-osv/issues/9).
This PR does not specify how to handle Kubernetes distributions by cloud vendors like EKS and GKE. We can talk about it here if needed, or merge it once and discuss it separately.
=> Add Kubernetes ecosystem

validation/schema.json
This commit adds the `upstream` field to the schema definition. It was omitted from #312
=> fix(jsonschema): add upstream field to schema definition

bindings/go/osvschema/constants.go, bindings/go/osvschema/vulnerability.go
Moving the struct definitions of the OSV record from [osv-scanner](https://github.com/google/osv-scanner/blob/b870d62b9987f27ab0212a9fd0eeef8086554699/pkg/models/vulnerability.go) to this repository, since it makes more sense to live in the `osvschema` module.
I've also added the new `upstream` field to the struct. It's probably worth having a discussion on how to make sure these structs remain in-sync with any future changes to the schema.
=> feat: add go struct definitions of OSV record

tools/osv-linter/internal/pkgchecker/ecosystems.go, tools/osv-linter/internal/pkgchecker/package_check.go, tools/osv-linter/internal/pkgchecker/package_check_test.go, tools/osv-linter/internal/pkgchecker/version_check.go
This PR enhances the linter by adding package existence checks for a variety of ecosystems:
- crates.io
- npm
- NuGet
- RubyGems
- Packagist
- Pub
- Hackage
- Maven
To accommodate these additions, the `ecosystems.go` file has been refactored, with code related to package existence checks moved to `package_check.go` and version checks moved to `version_check.go`. 
A current limitation is that malicious package record validation may fail, as these packages are often removed from package registries and are no longer queryable via API.
=> feat(linter): expand package checks across multiple ecosystems

tools/osv-linter/internal/checks/record.go, tools/osv-linter/internal/checks/record_test.go
Fix a confusing typo from "affected filed" to "affected field".
=> Fix typo in error message.

docs/schema.md, validation/schema.json
As per internal discussions, we are adding the "V8" prefix for policy-based synthetic vulnerability feeds to OSV schema.
The Chromium team has a [policy](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/security/updates.md) that states that direct embedders of Chromium packages such as V8 are responsible for using an up-to-date version of V8 packages. The definition of that is that the V8 package is at most one week old.
Since these types of packages do not have their own identifiers and therefore no advisory could be created, enforcement of such policies was not possible. We now created a synthetic advisory generator that takes such time-based policies and converts them into regularily updated advisories that OSV can read: …
=> Add V8 prefix.

docs/schema.md, validation/schema.json
=> Add Ubuntu severity type to the schema and docs

.github/workflows/validate-schema.yml
This pins the actions to their equivalent commit hashes to avoid disappointment like that seen for `tj-actions/changed-files` (that we managed to avoid being impacted by)
Signed-off-by: Andrew Pollock <apollock@google.com>
=> ci(workflow): pin actions to their commit hashes

tools/redhat/redhat_osv/osv.py, tools/redhat/testdata/OSV/RHSA-2024_4546.json, tools/redhat/testdata/OSV/RHSA-2024_6220.json
CVE upstream has moved from `related` to `upstream` to support https://github.com/ossf/osv-schema/pull/312 schema change. 
The `GO` vuln alias (for the CVE entry) has been left in related, so as not to affect the computation on the OSV.dev hierarchy display side. 
Tests updated to the latest schema version as well.
=> tools: Update redhat csaf2osv conversion to support upstream field + tests

docs/schema.json
This allows the JSON schema to be published alongside the rest of the documentation to GitHub pages. The schema will be available at https://ossf.github.io/osv-schema/schema.json.
Also created a symlink to the previous repository location of `validation/schema.json` in case anyone is already using that in a `$schema` property
Closes #226
=> Add symlink for `schema.json` to `docs`

CODE_OF_CONDUCT.md, CONTRIBUTING.md
This adds a CONTRIBUTING.md and CODE_OF_CONDUCT.md to address deficiencies and assist with progressing OSV Schema TI Graduation Application (https://github.com/ossf/tac/pull/456)
For want of something better, I used what is present at https://github.com/ossf/oss-vulnerability-guide
=> docs: add missing base documentation

tools/osv-linter/internal/pkgchecker/package_check_test.go
Some npm packages have been removed from upstream, causing test failures. Replace these packages with others.
=> fix: update npm package existence test

tools/osv-linter/README.md, tools/osv-linter/cmd/osv/main.go, tools/osv-linter/internal/checks/checks.go, tools/osv-linter/internal/checks/packages.go, tools/osv-linter/internal/checks/ranges.go, tools/osv-linter/internal/checks/record.go, tools/osv-linter/internal/checks/record_test.go, tools/osv-linter/internal/linter.go, tools/osv-linter/internal/pkgchecker/ecosystems.go
This PR adds some new validation checks for upstream, aliases, and related fields to help linux distro data validation
It also made several changes to streamline linter integration into the OSV data import pipeline:
- Error Code Refactoring: Error codes have been updated (e.g. from R0001 to RNG:001). This provides better clarity and scalability as we add more checks (e.g. distinguishing Range, Record, or Relation errors). The colon delimiter also simplifies parsing for users.
- fatal Check Collection: A fatal check collection is used to categorize critical validation failures. 
- JSON Output: Added a JSON output format to simplify programmatic parsing of validation results.
- added MinimOS ecosystem
=> feat(osv-linter): add checks for upstream and aliases fields

tools/osv-linter/internal/checks/packages.go, tools/osv-linter/internal/checks/ranges.go, tools/osv-linter/internal/checks/record.go
Fixes linter issues by:
- Skipping affected field checks for withdrawn records.
- Allowing records to have matching last_affected and introduced versions.
- Adding a mock version to ecosystem PURL strings when required
=> fix(linter): address linter issues on withdrawn records and range version and purl

CONTRIBUTING.md
'human readable' link was displaying incorrectly.
=> fix link in CONTRIBUTING.md

bindings/go/osvschema/constants.go
Ubuntu severity type was added to the schema in https://github.com/ossf/osv-schema/pull/337 and this PR updates the constants in Go bindings with Ubuntu severity type.
=> Update constants in Go bindings

validation/schema.json
missed `prefix` field in the schema in the previous PR
=> fix2: BellSoft DB prefix and Hardened Containers description (#361)

tools/osv-linter/internal/checks/schema_generated.json
This was missed in #364 - I've also opened #374 to ensure this can't slip through in future
=> fix: add `BELL` prefix to linter schema

scripts/update-ecosystems-lists.py
This should help with keeping the generated schema in sync and not require people to have Go setup to run `go generate`
=> chore: update generated schema when updating ecosystems

tools/osv-linter/internal/checks/schema_test.go
This should help ensure the two files are kept in sync - while this doesn't feel the best, it seemed slightly better than e.g. having a job that does a `diff` since we already run tests in a dedicated job
=> test: ensure that schema has been (re)generated

.github/workflows/checks.yml
I've just added this at the end of the test jobs since everything is so quick I don't think its worth having dedicated jobs for these
=> ci: ensure go files are formatted with `gofmt`

tools/osv-linter/internal/faulttolerant/http.go
This should make it easier for external services to accurately see how often they're being hit by the linter
=> feat: use a custom user agent when making requests

tools/osv-linter/internal/pkgchecker/ecosystems.go, tools/osv-linter/internal/pkgchecker/ecosystems_test.go, tools/osv-linter/internal/pkgchecker/package_check.go, tools/osv-linter/internal/pkgchecker/version_check.go
This adds support for checking that Ruby gems versions exist in the repository
=> feat: support checking if versions exist in RubyGems

docs/schema.md
There is an extra <tr> breaking table rendering, and also breaking the entire page after the table starts. 
I tried looking for a markdown validator to prevent this, but that seems to be not trivial.
Tested here: https://another-rex.github.io/osv-schema/
=> fix: Remove extra <tr>

tools/osv-linter/internal/pkgchecker/ecosystems.go, tools/osv-linter/internal/pkgchecker/ecosystems_test.go, tools/osv-linter/internal/pkgchecker/version_check.go
This adds support for checking that crates.io packages exist in the repository
=> feat: support checking if versions exist in crates.io

tools/osv-linter/internal/pkgchecker/version_check.go
The majority of implementations are the same just with different keys for getting the versions from the JSON response, so we can easily handle this in a single function
=> refactor: deduplicate "versions exist" logic

CONTRIBUTING.md, scripts/update-ecosystems-lists.py
Also updates the update-ecosystem-lists.py script to copy the schema.json file over to the linter. (This avoids people having to run go generate on the linter as an extra step)
=> docs: Update contributing doc with some detailed steps

README.md, bindings/go/osvschema/constants.go, docs/schema.md, ecosystems.json, tools/osv-linter/internal/checks/schema_generated.json, validation/schema.json
Issue reference: https://github.com/google/osv.dev/issues/3780
=> Add Echo Ecosystem

tools/osv-linter/go.mod, tools/osv-linter/go.sum
Notably this brings in https://github.com/google/osv-scalibr/pull/1168 and https://github.com/google/osv-scalibr/pull/1159 which unblocks https://github.com/ossf/osv-schema/pull/399 and https://github.com/ossf/osv-schema/pull/389 respectively
=> feat: update `osv-scalibr`

docs/schema.md, tools/osv-linter/internal/checks/schema_generated.json, validation/schema.json
OSV.dev is looking to decouple Debian and Alpine CVE Trackers from its main CVE-record. 
This PR adds the DEBIAN- prefix for use for CVEs tracked by Debian's security tracker to the schema.
=> feat: Added support for a DEBIAN- prefix

tools/osv-linter/internal/pkgchecker/ecosystems.go
=> fix: add `CRAN` to the list of supported ecosystems
