ossf/osv-schema

docs/schema.md, validation/schema.json
Includes validating:
- "repo" is required if range type is "GIT".
- "versions" is required if there are no SEMVER ranges. 
- There is at least once "introduced" event.
=> Add a JSON schema for validation.

tools/ghsa/Pipfile.lock, tools/ghsa/convert_ghsa.py, tools/ghsa/convert_ghsa_test.py, tools/ghsa/testdata/maven_greater_than.json, tools/ghsa/testdata/maven_greater_than.osv.json, tools/ghsa/testdata/npm_greater_than.json, tools/ghsa/testdata/npm_greater_than.osv.json
Use the OSV library to compute the next version to use as the
"introduced" version.
=> GHSA converter: Support ranges using >.

docs/schema.md
Make clear that the package type should be to a descriptive webpage and not a link to download artifact
=> Clarify intention of the PACKAGE type

docs/schema.md
Improve the pseudocode to cover matching `affected.versions` and
`affected.package` as well.
Link to this from earlier in the spec.
Clearing up some ambiguity pointed out in #27
=> Improve pseudocode for evaluation.

tools/debian/.pylintrc, tools/debian/Pipfile, tools/debian/Pipfile.lock, tools/debian/convert_debian.py
Also adds a markdownify dependency
=> Script for converting debian security tracker to osv format 

tools/debian/.pylintrc, tools/debian/.style.yapf, tools/debian/Pipfile, tools/debian/Pipfile.lock, tools/debian/README.md, tools/debian/convert_debian.py
First merge #47 which updates the readme with "WIP" and execution instruction
=> Debian converter script WIP

tools/debian/.pylintrc, tools/debian/.style.yapf, tools/debian/Pipfile, tools/debian/Pipfile.lock, tools/debian/README.md, tools/debian/convert_debian.py, tools/debian/first_package_finder.py
Adds the ability to have introduced version per Debian release. 
Adds method for git to retrieve last modified time (Commented out at the moment)
Formatted as Option 2 described in #24
=> Improved Debian Importer

tools/debian/convert_debian.py
Add the url of the debian security advisory for each osv json entry
=> Add reference entry to outputted json

tools/debian/Pipfile, tools/debian/README.md, tools/debian/convert_debian.py
Adds support for importing DTSA files.
The dateutil dependency is already included in the lock file from another dependency, so no lock file changes
=> Add support for DTSA

tools/debian/first_package_finder.py
Updates first_package_finder to only list the version found after the release date
=> First package after release finder

docs/schema.md
=> Update ID table in schema

docs/schema.md
Add alpine as a ecosystem entry in the osv schema
=> Add alpine as a ecosystem entry in the osv schema

docs/schema.md
=> Fix alpine shared format url

docs/schema.md
=> Clarify schema_version being required in >1.0.0

docs/schema.md, validation/schema.json
As per https://github.com/ossf/osv-schema/issues/125#issuecomment-1486206362
=> Added INTRODUCED to compliment FIX

docs/schema.md, validation/schema.json
Revisiting #89 
Partially Fixes #78
Related to #138
=> Add DETECTION reference type

docs/schema.md, validation/schema.json
not sure why the tab got mangled.
=> Last affected

README.md
Adds Bitnami reference to readme file.
=> [bitnami] Update readme

validation/schema.json
Signed-off-by: Kurt Seifried <kurt@seifried.org>
=> Fixed cvssv3 regex missing escape

docs/schema.md
=> Swap CRAN and bioconductor

validation/README.md
See: https://github.com/python-jsonschema/jsonschema/issues/600
=> Replace jsonschema with check-jsonschema

README.md, docs/schema.md
Signed-off-by: Caleb Brown <calebbrown@google.com>
=> Add Malicious Packages and the "MAL" id namespace.

validation/schema.json
Add more title attributes to the validation specifications to assist an unfamiliar reader with the intention behind them.
Also reformatted for consistency.
No functional changes.
=> Add more title attributes to improve casual comprehension

README.md, docs/schema.md
=> add initial reference for CGA (chainguard)

.github/workflows/validate-schema.yml, .gitignore
This will address the deficiency surfaced in #163
=> ci(workflow): add a GitHub Action to validate JSON schema changes

README.md, docs/schema.md, validation/schema.json
Add the `Red Hat` ecosystem, see https://github.com/google/osv.dev/issues/1404
=> Add Red Hat ecosystem

docs/schema.md, validation/schema.json
Also update OSV formatted URL for USN
Let me know if you think it should be `UBUNTU-CVE` instead
=> Add UBUNTU prefix

CHARTER.md
The final charter have been released by the LF formation team. 
Added the date and clean up the charter to match the official version of the charter.
=> Update charter to match official LF release.

validation/schema.json
=> fix(schema): add missing Chainguard ecosystem/prefix

tools/osv-linter/internal/pkgchecker/ecosystems.go, validation/schema.json
Also correct case on Chainguard ecosystem in linter
=> fix: add missing validation for Wolfi

docs/schema.md
With how ID prefixes are formatted.
=> Fix some minor formatting inconsistencies

tools/redhat/README.md
=> add extra documentaion on how Red Hat conversion works

.github/workflows/validate-schema.yml
This is the current latest version, with none of the breaking changes being impactful though [v44.0.0's is noteworthy for forks](https://github.com/tj-actions/changed-files/releases/tag/v44.0.0)
=> ci: update `tj-actions/changed-files`

docs/schema.md
Resolves https://github.com/ossf/osv-schema/issues/325
=> docs: point to vector string documentation

bindings/go/osvschema/constants.go
=> fix(bindings/go): remove `//nolint:gosec` from `constants.go`

docs/schema.md, validation/schema.json
Add Ubuntu LSN https://ubuntu.com/security/livepatch as discussed in https://github.com/google/osv.dev/issues/3204
=> feat: add Ubuntu LSN

GUIDING_PRINCIPLES.md
This document codifies some of the guiding principles that went into the OSV schema, in preparation for the OpenSSF "Graduated" application.
=> Add GUIDING_PRINCIPLES.md

tools/osv-linter/internal/pkgchecker/ecosystems.go, tools/osv-linter/internal/pkgchecker/ecosystems_test.go, tools/osv-linter/internal/pkgchecker/package_check.go, tools/osv-linter/internal/pkgchecker/version_check.go
This should hopefully make it a bit easier to find stuff especially as support for more ecosystems is added
=> refactor: order ecosystem stuff alphabetically

tools/osv-linter/internal/pkgchecker/ecosystems.go, tools/osv-linter/internal/pkgchecker/ecosystems_test.go, tools/osv-linter/internal/pkgchecker/version_check.go
This adds support for checking that NPM packages exist in the repository
=> feat: support checking if versions exist in NPM

tools/osv-linter/go.mod, tools/osv-linter/go.sum
Among other things this includes https://github.com/google/osv-scalibr/pull/1196 which will unblock #407
=> feat: update `osv-scalibr`

RELEASING.md
This is part of the OSV-Schema graduation process here: https://github.com/ossf/tac/pull/456/files#r2170156318
=> Add a releasing.md file

tools/osv-linter/internal/pkgchecker/ecosystems.go, tools/osv-linter/internal/pkgchecker/ecosystems_test.go, tools/osv-linter/internal/pkgchecker/version_check.go
This adds support for checking that Hackage packages exist in the repository
=> feat: support checking if versions exist in Hackage
